import "../styles/global.scss";
import "bootstrap/dist/css/bootstrap.css";
import Navbar from "@/src/components/Nav/Navbar";
import { Poppins } from "next/font/google";
import classNames from "classnames";
import { Suspense } from "react";
import GlobalLoader from "@/src/components/GlobalLoader/GlobalLoader";
import { ToastNotificationProvider } from "@/src/contexts/ToastNotificationContext";
import { AuthContextProvider } from "@/src/contexts/AuthContext";

const poppins = Poppins({
  style: "normal",
  weight: ["300", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Nexusphere AI</title>
        <meta name="Nexusphere AI" content="Welcome Nexusphere AI" />
      </head>
      <body className={classNames(poppins.className, "bg-dark")}>
        <AuthContextProvider>
          <ToastNotificationProvider>
            <Suspense fallback={<GlobalLoader />}>
              <Navbar />
              {children}
            </Suspense>
          </ToastNotificationProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
