name: Build verify

on:
  pull_request:
    branches: [] #add branch

jobs:
  build-ui:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Add env file
        run: |
          cd ./client/
          touch .env.production
          echo NEXT_PUBLIC_CLIENT_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_API_KEY }} >> .env.production
          echo NEXT_PUBLIC_CLIENT_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_AUTH_DOMAIN }} >> .env.production
          echo NEXT_PUBLIC_CLIENT_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_PROJECT_ID }} >> .env.production 
          echo NEXT_PUBLIC_CLIENT_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_STORAGE_BUCKET }} >> .env.production
          echo NEXT_PUBLIC_CLIENT_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_MESSAGING_SENDER_ID }} >> .env.production
          echo NEXT_PUBLIC_CLIENT_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_APP_ID }} >> .env.production
          echo NEXT_PUBLIC_CLIENT_ENDPOINT_URL=${{ secrets.NEXT_PUBLIC_CLIENT_ENDPOINT_URL }} >> .env.production
          echo NEXT_PUBLIC_CLIENT_IMAGE_HOST_URL=${{ secrets.NEXT_PUBLIC_CLIENT_IMAGE_HOST_URL }} >> .env.production
          cat .env.production

      - name: Npm install
        run: |
          cd ./client/
          npm ci --production

      - name: Npm run Build
        run: |
          cd ./client/
          npm run build
