name: Deploy to Azure RegistryContainer

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-ui:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Add env file
        run: |
          cd ./client/
          touch .env
          echo NEXT_PUBLIC_CLIENT_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_API_KEY }} >> .env
          echo NEXT_PUBLIC_CLIENT_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_AUTH_DOMAIN }} >> .env
          echo NEXT_PUBLIC_CLIENT_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_PROJECT_ID }} >> .env 
          echo NEXT_PUBLIC_CLIENT_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_STORAGE_BUCKET }} >> .env
          echo NEXT_PUBLIC_CLIENT_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_MESSAGING_SENDER_ID }} >> .env
          echo NEXT_PUBLIC_CLIENT_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_APP_ID }} >> .env
          cat .env

      - name: Build
        run: |
          cd ./client/
          npm install
          npm run build

      - name: Login to Azure Container registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_ENDPOINT }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build & push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.AZURE_REGISTRY_ENDPOINT }}/openai:latest
          file: ./client/Dockerfile
