name: Deploy to Azure RegistryContainer

on:
  push:
    branches: [] #add branch

jobs:
  build-ui:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure Container registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_ENDPOINT }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build & push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.AZURE_REGISTRY_ENDPOINT }}/openai:latest
          file: ./client/Dockerfile
          build-args: |
            NEXT_PUBLIC_CLIENT_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_API_KEY }} 
            NEXT_PUBLIC_CLIENT_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_AUTH_DOMAIN }} 
            NEXT_PUBLIC_CLIENT_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_PROJECT_ID }}  
            NEXT_PUBLIC_CLIENT_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_STORAGE_BUCKET }} 
            NEXT_PUBLIC_CLIENT_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_MESSAGING_SENDER_ID }} 
            NEXT_PUBLIC_CLIENT_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_CLIENT_FIREBASE_APP_ID }}
            NEXT_PUBLIC_CLIENT_ENDPOINT_URL=${{ secrets.NEXT_PUBLIC_CLIENT_ENDPOINT_URL }}
            NEXT_PUBLIC_CLIENT_IMAGE_HOST_URL=${{ secrets.NEXT_PUBLIC_CLIENT_IMAGE_HOST_URL }}
